### ISSUE TITLE
shellcheck

### ISSUE THREAD

**Issue by ghost** [hamadmarri/ntn#1]
Why don't you use shellcheck? [shellcheck.net](https://www.shellcheck.net) can be used to capture bugs in the [ntn](https://github.com/hamadmarri/ntn/blob/master/ntn) shell script. I've invoked shellcheck on the [ntn](https://github.com/hamadmarri/ntn/blob/master/ntn) script and it reported a bunch of issues (which should be fixed).

**Comment by hamadmarri** [comment]
Hi @m0lese 

Sure, I will fix the script.

Thank you so much  :+1:
